from .demo_view import DemoView
from .user_view import UserDetailAPIView
from .user_view import UserListCreateAPIView
from .store_view import StoreListCreateView
from .store_view import StoreDetailView
from .store_category_view import StoreCategoryListCreateView
from .store_category_view import StoreCategoryDetailView
from .service_view import *
from .product_view import *
from .product_category_view import *
from .product_sub_category_view import *
from .service_booking_view import *
from .email_track_view import *