from .demo_view import DemoView
from .user_view import UserDetailAPIView
from .user_view import UserListCreateAPIView
from .service_view import ServiceListCreateAPIView,ServiceDetailAPIView,ServiceTypeListCreateAPIView,ServiceTypeDetailAPIView